// lib/waybill/exportPdf.ts
//
// Builds a combined PDF for a single Waybill:
//   - cover page: id, origin/vendor/amount, status, current stage
//   - audit trail page(s): one row per waybill_events row
//   - attachment page(s): concatenated via pdf-lib.copyPages
//
// JPG attachments are converted via sharp → JPEG buffer → embedded as
// full-page image (covers the entire letter/A4 page). PDF attachments
// are merged with copyPages(). Rejected if no copyPages support (we
// wrap a try/catch per file).

import 'server-only';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import sharp from 'sharp';
import { get } from '../slips/storage';
import type { WaybillRow } from '../../web-admin/src/lib/server/waybill';
import type { WaybillEventRow } from './events';
import type { WaybillAttachmentRow } from './attachments';
import { stageLabel } from './labels';

// pdf-lib's StandardFonts only support WinAnsi; characters outside that
// range (e.g. Thai/CJK) throw "WinAnsi cannot encode U+XXXX".  As a
// pragmatic short-term fix, transliterate to '?' so the PDF is always
// renderable; lossless Thai/CJK support requires embedding a TTF (deferred).
function safe(s: string | null | undefined): string {
  if (s == null) return '—';
  return s
    .normalize('NFKD')
    .replace(/[^\x09\x0A\x0D\x20-\x7E\u00A0-\u00FF]/g, '?');
}

export interface BuildPdfOptions {
  waybill: WaybillRow;
  events: WaybillEventRow[];
  attachments: WaybillAttachmentRow[];
  /** Per-attachment id (string) selection; null = include all */
  includeAttachmentIds?: ReadonlySet<string> | null;
  /** Include these top sections; default all */
  include?: { cover?: boolean; rail?: boolean; audit?: boolean; attachments?: boolean };
  pageSize?: 'A4' | 'Letter';
}

export async function buildWaybillPdf(opts: BuildPdfOptions): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`Waybill ${opts.waybill.id}`);
  pdf.setAuthor('World ERP');
  pdf.setProducer('world-erp/lib/waybill/exportPdf');

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const pageSize = opts.pageSize ?? 'Letter';
  const A4: [number, number] = [595.28, 841.89];
  const LETTER: [number, number] = [612, 792];
  const dims = pageSize === 'A4' ? A4 : LETTER;
  const [W, H] = dims;

  const inc = {
    cover: true,
    rail: true,
    audit: true,
    attachments: true,
    ...(opts.include ?? {}),
  };

  const meta = {
    id: opts.waybill.id,
    origin: opts.waybill.origin,
    origin_id: opts.waybill.origin_id,
    vendor: safe(opts.waybill.vendor_name),
    amount: safe(opts.waybill.total_amount),
    currency: safe(opts.waybill.currency),
    status: safe(opts.waybill.status),
    stage: stageLabel(opts.waybill.current_stage, opts.waybill.origin === 'expense' ? 'expense' : 'procurement', 'en').label,
    submitted: opts.waybill.created_at.toISOString(),
    updated: opts.waybill.updated_at.toISOString(),
  };

  if (inc.cover) addCover(pdf, font, fontBold, dims, meta);
  if (inc.rail)  addRail(pdf, font, fontBold, dims, opts);
  if (inc.audit) addAudit(pdf, font, fontBold, dims, opts.events);

  if (inc.attachments) {
    const all = opts.attachments ?? [];
    const list = opts.includeAttachmentIds == null
      ? all
      : all.filter((a) => opts.includeAttachmentIds!.has(String(a.id)));
    for (const att of list) {
      await addAttachment(pdf, dims, att);
    }
  }

  return pdf.save();
}

function drawText(
  page: import('pdf-lib').PDFPage,
  text: string,
  x: number,
  y: number,
  font: import('pdf-lib').PDFFont,
  size: number,
  color: { r: number; g: number; b: number } = { r: 0, g: 0, b: 0 },
) {
  try {
    page.drawText(text, { x, y, font, size, color: rgb(color.r, color.g, color.b) });
  } catch {
    page.drawText(safe(text), { x, y, font, size, color: rgb(color.r, color.g, color.b) });
  }
}

function addCover(
  pdf: PDFDocument,
  font: import('pdf-lib').PDFFont,
  fontBold: import('pdf-lib').PDFFont,
  [W, H]: [number, number],
  meta: {
    id: string; origin: string; origin_id: number; vendor: string;
    amount: string; currency: string; status: string; stage: string;
    submitted: string; updated: string;
  },
) {
  const page = pdf.addPage([W, H]);
  let y = H - 80;

  drawText(page, 'World ERP — Waybill', 60, y, fontBold, 22);
  y -= 36;
  drawText(page, meta.id, 60, y, font, 16);
  y -= 24;
  drawText(page, `Origin: ${meta.origin} ${meta.origin_id}`, 60, y, font, 12);
  y -= 18;
  drawText(page, `Vendor: ${meta.vendor}`, 60, y, font, 12);
  y -= 18;
  drawText(page, `Amount: ${meta.amount} ${meta.currency}`, 60, y, font, 12);
  y -= 18;
  drawText(page, `Status: ${meta.status} · Stage: ${meta.stage}`, 60, y, font, 12);
  y -= 18;
  drawText(page, `Submitted: ${meta.submitted}`, 60, y, font, 10);
  y -= 14;
  drawText(page, `Updated: ${meta.updated}`, 60, y, font, 10);
  y -= 30;
  drawText(page, 'Generated by world-erp/web-admin · See /my-waybills for the live view.', 60, y, font, 9, { r: 0.4, g: 0.4, b: 0.4 });
}

function addRail(
  pdf: PDFDocument,
  font: import('pdf-lib').PDFFont,
  fontBold: import('pdf-lib').PDFFont,
  [W, H]: [number, number],
  opts: BuildPdfOptions,
) {
  const pips = (
    opts.waybill.origin === 'expense'
      ? ['submission','dept_verification','dept_authorization','accounting_verification','accounting_supervision','accounting_authorization','disbursement_authorization','cfo_authorization','ceo_authorization','awaiting_disbursement','disbursed']
      : ['submission','dept_verification','accounting_authorization','cfo_authorization','disbursed']
  ) as string[];
  const stageIndex = pips.indexOf(opts.waybill.current_stage);
  const domain: 'expense' | 'procurement' = opts.waybill.origin === 'expense' ? 'expense' : 'procurement';

  const page = pdf.addPage([W, H]);
  let y = H - 80;
  drawText(page, 'Pipeline Rail', 60, y, fontBold, 18);
  y -= 28;

  for (let i = 0; i < pips.length; i++) {
    const sk = pips[i];
    const meta = stageLabel(sk, domain, 'en');
    let state = 'pending';
    if (sk === 'disbursed' && opts.waybill.status === 'completed') state = 'passed';
    if (stageIndex > -1 && i < stageIndex) state = 'passed';
    if (stageIndex > -1 && i === stageIndex) state = 'active';

    const tag = `(${i + 1})`;
    drawText(page, `${tag} ${state.toUpperCase()}  ${meta.emoji}  ${meta.label}`, 60, y, font, 11);
    y -= 16;
    if (y < 60) {
      drawText(page, '… (continued on next page)', 60, y, font, 9, { r: 0.4, g: 0.4, b: 0.4 });
      break;
    }
  }
}

function addAudit(
  pdf: PDFDocument,
  font: import('pdf-lib').PDFFont,
  fontBold: import('pdf-lib').PDFFont,
  [W, H]: [number, number],
  events: WaybillEventRow[],
) {
  let page = pdf.addPage([W, H]);
  let y = H - 80;
  drawText(page, 'Audit Trail', 60, y, fontBold, 18);
  y -= 28;

  const header = ['#', 'Kind', 'From → To', 'Actor', 'At'];
  const colX = [60, 100, 220, 360, 460];
  header.forEach((h, i) => drawText(page, h, colX[i], y, fontBold, 10));
  y -= 14;
  page.drawLine({ start: { x: 60, y }, end: { x: W - 60, y }, thickness: 0.5, color: rgb(0.5, 0.5, 0.5) });
  y -= 14;

  for (const e of events) {
    if (y < 60) {
      page = pdf.addPage([W, H]);
      y = H - 80;
      header.forEach((h, i) => drawText(page, h, colX[i], y, fontBold, 10));
      y -= 14;
      page.drawLine({ start: { x: 60, y }, end: { x: W - 60, y }, thickness: 0.5 });
      y -= 14;
    }
    const cells = [
      `#${e.sequence}`,
      safe(e.kind),
      `${safe(e.stage_from) || '—'} → ${safe(e.stage_to) || '—'}`,
      String(e.actor_id ?? ''),
      (e.occurred_at instanceof Date ? e.occurred_at : new Date(e.occurred_at)).toISOString(),
    ];
    cells.forEach((c, i) => drawText(page, truncate(c, 32), colX[i], y, font, 9));
    y -= 14;
  }
}

async function addAttachment(
  pdf: PDFDocument,
  [W, H]: [number, number],
  att: WaybillAttachmentRow,
): Promise<void> {
  let buf: Buffer;
  try {
    buf = (await get(att.storage_key)) as Buffer;
  } catch {
    addErrorPage(pdf, [W, H], `Could not fetch attachment #${att.id} (${att.storage_key})`);
    return;
  }

  const ct = (att.content_type ?? '').toLowerCase();
  if (ct.includes('pdf')) {
    try {
      const src = await PDFDocument.load(buf as Uint8Array);
      const pages = await pdf.copyPages(src, src.getPageIndices());
      pages.forEach((p: import('pdf-lib').PDFPage) => pdf.addPage(p));
    } catch (err) {
      addErrorPage(pdf, [W, H], `Could not merge PDF attachment '${att.filename}' — ${(err as Error).message}`);
    }
    return;
  }

  if (ct.startsWith('image/')) {
    try {
      const pngBuf = await sharp(buf).resize({ width: 1024, withoutEnlargement: true }).png().toBuffer();
      const img = await pdf.embedPng(pngBuf);
      const page = pdf.addPage([W, H]);
      const scale = Math.min((W - 120) / img.width, (H - 120) / img.height);
      const w = img.width * scale;
      const h = img.height * scale;
      page.drawImage(img, { x: (W - w) / 2, y: (H - h) / 2, width: w, height: h });
      const f = await pdf.embedFont(StandardFonts.Helvetica);
      drawText(page, safe(att.filename), 60, 30, f, 9);
    } catch (err) {
      addErrorPage(pdf, [W, H], `Could not embed image '${att.filename}' — ${(err as Error).message}`);
    }
    return;
  }

  addErrorPage(pdf, [W, H], `Unsupported attachment content_type '${att.content_type}' for ${att.filename}`);
}

async function addErrorPage(pdf: PDFDocument, [W, H]: [number, number], msg: string): Promise<void> {
  const page = pdf.addPage([W, H]);
  const font = await pdf.embedFont(StandardFonts.Helvetica).catch(() => null);
  const writeText = (s: string): void => {
    try {
      page.drawText(s, { x: 60, y: H - 80, font: font as import('pdf-lib').PDFFont, size: 10, color: rgb(0.6, 0, 0) });
    } catch {
      page.drawText(safe(s), { x: 60, y: H - 80, font: font as import('pdf-lib').PDFFont, size: 10, color: rgb(0.6, 0, 0) });
    }
  };
  writeText('[!] ' + msg);
}

function truncate(s: string, n: number): string {
  return s.length <= n ? s : s.slice(0, n - 1) + '…';
}
