import Link from 'next/link';
import type { ExecutiveFinance } from '@/finance/reporting';

const money = (value: number) => value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

function Kpi({ label, value, href, tone = 'text-ink', hint }: { label: string; value: string; href: string; tone?: string; hint?: string }) {
  return <Link className="panel-elevated block p-4 transition-transform hover:-translate-y-0.5" href={href}><div className="text-xs font-bold uppercase tracking-wider text-mute">{label}</div><div className={`mt-2 text-2xl font-black tabular-nums ${tone}`}>{value}</div>{hint && <div className="mt-1 text-xs text-ink-2">{hint}</div>}</Link>;
}

export function ExecutiveFinanceDashboard({ data }: { data: ExecutiveFinance }) {
  const reportQuery = `from=${data.filters.dateFrom}&to=${data.filters.dateTo}${data.filters.branchId ? `&branch=${data.filters.branchId}` : ''}`;
  const maxTrend = Math.max(1, ...data.revenueTrend.map((item) => Math.abs(item.revenue)));
  return <div className="space-y-5">
    <section><div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg font-bold text-ink">Posted actuals</h2><p className="text-sm text-ink-2">Live values from approved, posted journals and controlled subledgers.</p></div><span className="glass-chip text-positive">Posted only</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Revenue" value={`THB ${money(data.actual.revenue)}`} href={`/reports?report=profit_and_loss&${reportQuery}`} tone="text-positive" /><Kpi label="Gross margin" value={`THB ${money(data.actual.grossMargin)}`} href={`/reports?report=gross_margin&${reportQuery}`} hint={data.actual.revenue ? `${(data.actual.grossMargin / data.actual.revenue * 100).toFixed(1)}% of revenue` : 'No posted revenue'} tone={data.actual.grossMargin >= 0 ? 'text-positive' : 'text-critical'} /><Kpi label="Net income" value={`THB ${money(data.actual.netIncome)}`} href={`/reports?report=profit_and_loss&${reportQuery}`} tone={data.actual.netIncome >= 0 ? 'text-positive' : 'text-critical'} /><Kpi label="Cash" value={`THB ${money(data.actual.cash)}`} href={`/reports?report=cash_flow&${reportQuery}`} hint={`${data.actual.reconciledPercent.toFixed(1)}% statement rows reconciled`} /></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Accounts receivable" value={`THB ${money(data.actual.ar)}`} href={`/reports?report=ar_aging&${reportQuery}`} /><Kpi label="Accounts payable" value={`THB ${money(data.actual.ap)}`} href={`/reports?report=ap_aging&${reportQuery}`} tone="text-caution" /><Kpi label="Inventory value" value={`THB ${money(data.actual.inventory)}`} href={`/reports?report=inventory&${reportQuery}`} hint={`${data.stock.turnover.toFixed(2)}× annualized turnover`} /><Kpi label="30-day cash forecast" value={`THB ${money(data.actual.forecastCash)}`} href={`/reports?report=cash_forecast&${reportQuery}`} tone={data.actual.forecastCash >= 0 ? 'text-positive' : 'text-critical'} /></section>
    <section className="panel-elevated p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Revenue and gross margin</h2><p className="text-sm text-ink-2">Posted monthly activity for the selected period.</p></div><Link className="glass-chip" href={`/ledger?${reportQuery}`}>Drill to ledger</Link></div>{data.revenueTrend.length ? <div className="mt-5 flex h-52 items-end gap-4 border-b border-rule px-2">{data.revenueTrend.map((item) => <div className="flex h-full flex-1 flex-col items-center justify-end gap-2" key={item.period}><div className="text-xs font-mono text-ink-2">{money(item.revenue)}</div><div className="flex w-full items-end justify-center gap-1"><div className="w-5 rounded-t bg-accent" style={{ height: `${Math.max(3, Math.abs(item.revenue) / maxTrend * 150)}px` }} title={`Revenue ${money(item.revenue)}`} /><div className="w-5 rounded-t bg-positive" style={{ height: `${Math.max(3, Math.abs(item.grossMargin) / maxTrend * 150)}px` }} title={`Gross margin ${money(item.grossMargin)}`} /></div><div className="pb-2 text-xs font-mono text-mute">{item.period}</div></div>)}</div> : <p className="mt-5 rounded-md border border-dashed border-rule p-8 text-center text-sm text-mute">No posted revenue in this period.</p>}</section>
    <div className="grid gap-5 xl:grid-cols-2"><Aging title="AR aging" rows={data.arAging} href={`/reports?report=ar_aging&${reportQuery}`} /><Aging title="AP aging" rows={data.apAging} href={`/reports?report=ap_aging&${reportQuery}`} /></div>
    <div className="grid gap-5 lg:grid-cols-3"><section className="panel-elevated p-5"><h2 className="text-lg font-bold">Inventory health</h2><dl className="mt-4 space-y-3 text-sm"><Row label="Quantity on hand" value={data.stock.quantity.toLocaleString()} /><Row label="Stock value" value={`THB ${money(data.stock.value)}`} /><Row label="Expiring in 90 days" value={`THB ${money(data.stock.expiringValue)}`} /><Row label="Annualized turnover" value={`${data.stock.turnover.toFixed(2)}×`} /></dl></section><section className="panel-elevated p-5"><h2 className="text-lg font-bold">Budget and FX</h2><dl className="mt-4 space-y-3 text-sm"><Row label="Approved budget" value={`THB ${money(data.actual.budget)}`} /><Row label="Budget variance" value={`THB ${money(data.actual.budgetVariance)}`} /><Row label="Foreign-currency exposure" value={`THB ${money(data.actual.fxExposureThb)}`} /><Row label="Bank reconciliation" value={`${data.actual.reconciledPercent.toFixed(1)}%`} /></dl></section><section className="panel-elevated p-5"><h2 className="text-lg font-bold">Control tie-outs</h2><div className="mt-4 space-y-2"><Control label="Debits equal credits" ok={data.tieOuts.journalsBalanced} detail={`${money(data.tieOuts.debits)} / ${money(data.tieOuts.credits)}`} /><Control label="Balance sheet equation" ok={data.tieOuts.balanceSheetTied} detail={`${money(data.tieOuts.assets)} / ${money(data.tieOuts.liabilitiesEquity)}`} /><Control label="AR control = subledger" ok={data.tieOuts.arTied} /><Control label="AP control = subledger" ok={data.tieOuts.apTied} /><Control label="Inventory GL = valuation" ok={data.tieOuts.inventoryTied} /></div></section></div>
    <section className="rounded-md border border-caution bg-caution-soft p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-ink">Operational pipeline · not posted actuals</h2><p className="text-sm text-ink-2">Commitments and drafts are forecast context only and never included in financial statements.</p></div><span className="glass-chip text-caution">Unposted</span></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><Kpi label="Open sales orders" value={`THB ${money(data.pipeline.openSales)}`} href="/sales" /><Kpi label="Open procurement" value={`THB ${money(data.pipeline.openProcurement)}`} href="/po" /><Kpi label="Unposted expenses" value={`THB ${money(data.pipeline.unpostedExpenses)}`} href="/expense" /></div></section>
  </div>;
}

function Aging({ title, rows, href }: { title: string; rows: ExecutiveFinance['arAging']; href: string }) {
  const total = rows.reduce((sum, row) => sum + row.amount, 0);
  return <section className="panel-elevated p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><Link className="text-sm text-accent" href={href}>View report</Link></div><div className="mt-4 space-y-3">{rows.map((row) => <div key={row.bucket}><div className="flex justify-between text-sm"><span>{row.bucket.replace('_', '–')} · {row.count} docs</span><span className="font-mono">{money(row.amount)}</span></div><div className="mt-1 h-2 overflow-hidden rounded bg-paper-2"><div className="h-full bg-accent" style={{ width: `${total ? Math.max(2, row.amount / total * 100) : 0}%` }} /></div></div>)}{!rows.length && <p className="text-sm text-mute">No open documents.</p>}</div></section>;
}

function Row({ label, value }: { label: string; value: string }) {
  return <div className="flex items-center justify-between gap-4"><dt className="text-ink-2">{label}</dt><dd className="font-mono font-bold text-ink">{value}</dd></div>;
}

function Control({ label, ok, detail }: { label: string; ok: boolean; detail?: string }) {
  return <div className="flex items-start justify-between gap-3 rounded-md border border-rule bg-paper-2 p-3 text-sm"><div><div>{label}</div>{detail && <div className="mt-1 font-mono text-xs text-mute">{detail}</div>}</div><span className={ok ? 'font-bold text-positive' : 'font-bold text-critical'}>{ok ? 'Tied' : 'Review'}</span></div>;
}
